Handle media player network errors and try to recover
benwiley4000/react-responsive-audio-player pull request #426
Opened 2019-06-09 16:40 UTC by danielr18

Fixes #425.

The logic is that when the player gets a network error, it checks if it's online to try and reload the active track, and if it's not, it listens to the [online event](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events) and once the player is back online, it will try to reload.

The reload track method has an option to auto play the track, however I'm not sure if we should auto play after the error, the player becomes paused after the error, maybe it's best to just reload and leave it paused? Might be weird if you were offline for a considerate amount of time and then when you go back online, something starts playing.

The `online` event listener is removed:
- The event handler is called.
- The active track changes.
- The component unmounts.

@benwiley4000 Let me know what you think.

2019-06-09 16:45 UTC, danielr18 commented
I believe the `reloadActiveTrack` could be put in the control props. It would allow users to add a reload button when `mediaCannotPlay` is set. If you are offline and try to play a track, `mediaCannotPlay` will be true, and you can't play it again without changing tracks even after you become online.

2019-06-11 14:41 UTC, benwiley4000 requested changes
This is looking really good, thank you! And sorry for the delay in reviewing this.

> The reload track method has an option to auto play the track, however I'm not sure if we should auto play after the error, the player becomes paused after the error, maybe it's best to just reload and leave it paused? Might be weird if you were offline for a considerate amount of time and then when you go back online, something starts playing.

> I believe the `reloadActiveTrack` could be put in the control props. It would allow users to add a reload button when mediaCannotPlay is set. If you are offline and try to play a track, mediaCannotPlay will be true, and you can't play it again without changing tracks even after you come back online.

Both great points! I think if we include this control prop then it would obviate the need for the autoplay behavior. I suggest we go with that!

2019-06-11 14:41 UTC, benwiley4000 commented on packages/core/src/PlayerContextProvider.js
> +    if (event.target === this.media && error && error.code === 2) {
Can we have a constant for the error code somewhere so we know which error type `2` is referencing?

2019-06-12 01:02 UTC, danielr18 commented
Just made the changes, feel free to modify the documentation of the new control prop if you want to improve it.

2019-06-12 01:12 UTC, benwiley4000 commented
Great thank you! I'll try to release this soon.

2019-06-12 01:12 UTC, merged

2019-06-12 22:07 UTC, benwiley4000 commented
@danielr18 released in v2.0.0-beta.2!